version: '3.4'
services:
  web:
    build:
      context: .
      target: dev
    ports:
      - 8080:8080
    volumes:
      - ./src:/app/src
      - ./yarn-cache:/usr/local/share/.cache/yarn/v1
    stdin_open: true
    tty: true