language: node_js
node_js:
  - "stable"
cache:
  directories:
  - $HOME/client/node_modules
before_script:
  - cd client
  - yarn install
script:
  - yarn -v
  # - yarn build
# deploy:
#   provider: pages
#   skip_cleanup: true
#   github_token: $github_token
#   local_dir: build
#   on:
#     branch: master