apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  labels:
    app: server
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: docker.io/DOCKER_USERNAME/IMAGE:TAG
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_HOST
              value: postgres
          envFrom:
            - configMapRef:
                name: postgres-configmap
          ports:
            - containerPort: 8000
          resources:
            requests:
              memory: 50Mi
              cpu: 10m

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres
          envFrom:
            - configMapRef:
                name: postgres-configmap
          ports:
            - containerPort: 5432
          resources:
            requests:
              memory: 50Mi
              cpu: 10m
