apiVersion: apps/v1
kind: Deployment
metadata:
  name: ipu-client
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: nginx-client
          image: docker.io/DOCKER_USERNAME/ipu-client:TAG
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          resources:
            requests:
              memory: 5Mi
              cpu: 1m
          volumeMounts:
            - mountPath: /etc/nginx/conf.d
              name: nginx-config
          readinessProbe:
            httpGet:
              port: 8000
              path: /
              scheme: http
              host: 0.0.0.0
            successThreshold: 1
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3

      volumes:
        - name: nginx-cofig
          configMap:
            name: nginx-config
            items:
              - key: default.conf
                path: default.conf
