version: '3'
services: 
  server:
    build: src
    container_name: server
    ports: 
      - "8000:8000"
    env_file: src/.env
    environment:
      - PYTHONUNBUFFERED=1
    restart: on-failure

  db:
    container_name: db
    image: postgres:11.2
    env_file:
      - src/.env
