version: '3'
services: 
  server:
    build: app
    container_name: server
    ports: 
      - "8000:8000"
    env_file: app/.env
    environment:
      - PYTHONUNBUFFERED=1
    restart: on-failure
    entrypoint:
      - "./entry.sh"
      - "uwsgi"
      - "--http"
      - ":8000"
      - "--gevent"
      - "1000"
      - "--http-websockets"
      - "--master"
      - "--wsgi-file"
      - "server.py"
      - "--callable app"

  db:
    container_name: db
    image: postgres:11.2
    env_file:
      - app/.env
