version: '3'
services: 
  server:
    build: .
    container_name: server
    ports: 
      - "8000:8000"
    env_file: .env
    environment:
      - PYTHONUNBUFFERED=1
    restart: on-failure
    entrypoint:
      - ./entry.sh
      - python
      - server.py

  db:
    container_name: db
    image: postgres:11.2
    env_file:
      - .env
