apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-socket-server
  labels:
    app: web-socket-server
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  replicas: 1
  selector:
    matchLabels:
      app: web-socket-server
  template:
    metadata:
      labels:
        app: web-socket-server
    spec:
      containers:
        - name: web-socket-server
          image: docker.io/DOCKER_USERNAME/IMAGE:TAG
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_HOST
              value: postgres
          envFrom:
            - configMapRef:
                name: postgres-configmap
          ports:
            - containerPort: 8000
          resources:
            requests:
              memory: 5Mi
              cpu: 1m
          readinessProbe:
            tcpSocket:
              port: 8000
            successThreshold: 1
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres
          envFrom:
            - configMapRef:
                name: postgres-configmap
          ports:
            - containerPort: 5432
          resources:
            requests:
              memory: 5Mi
              cpu: 1m
