apiVersion: v1
kind: Service
metadata:
  name: web-socket-server
spec:
  selector:
    app: web-socket-server
  type: NodePort
  ports:
  - port: 8000
    nodePort: 31420
    targetPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
