[package]
name = "plugin_market"
version = "0.1.0"
authors = ["hamadakafu <kafu.h1998@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "1.0.0-beta.4"
http = "0.1.17"
failure = "0.1.5"
serde = {version = "1.0.91", features = ["derive"]}
json = "0.11.13"
futures = "0.1.27"