apiVersion: v1
kind: Service
metadata:
  name: server
spec:
  selector:
    app: server
  # type: LoadBalancer
  # loadBalancerIP: 35.201.98.182
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
