apiVersion: v1
kind: Pod
metadata:
  name: server
  labels:
    app: server
spec:
  containers:
  - name: server
    image: docker.io/DOCKER_USERNAME/IMAGE:TAG
    imagePullPolicy: IfNotPresent
    env:
    - name: POSTGRES_HOST
      value: postgres
    envFrom:
    - configMapRef:
        name: postgres-configmap
    ports:
    - containerPort: 8000

---
apiVersion: v1
kind: Pod
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  containers:
  - name: postgres
    image: postgres
    envFrom:
    - configMapRef:
        name: postgres-configmap
    ports:
    - containerPort: 5432
